version: '3'

services:
  scheduler:
    # image: "ml:v1"
    build: .
    hostname: scheduler
    container_name: scheduler
    environment:
      - DMLC_PS_ROOT_URI=''
      - DMLC_PS_ROOT_PORT=9000
      - DMLC_ROLE='scheduler'
      - DMLC_NUM_SERVER=${SERVER_NUM}
      - DMLC_NUM_WORKER=${WORKER_NUM}
    volumes:
      -"/data/:/data/"
    networks:
        mlnet:
          ipv4_address: 172.30.0.2

  
  server:
    image: "ml:v1"
    depends_on:
      - scheduler
    hostname: server
    container_name: server
    environment:
      - DMLC_PS_ROOT_URI='172.30.0.2'
      - DMLC_PS_ROOT_PORT=9000
      - DMLC_ROLE='server'
    volumes:
      -"/data/:/data/"
    networks:
      - mlnet

  worker:
    image: "ml:v1"
    depends_on:
      - scheduler
    hostname: worker
    container_name: worker
    environment:
      - DMLC_PS_ROOT_URI='172.30.0.2'
      - DMLC_PS_ROOT_PORT=9000
      - DMLC_ROLE='worker'
    volumes:
      -"/data/:/data/"
    networks:
      - mlnet

networks:
  mlnet:
    driver: overlay
    ipam:
      config:
        - subnets: 172.30.0.0/55
          gateway: 172.30.0.1
